query GetTournamentSeatingChart($tournamentId: UUID!) {
  tournamentSeatingChart(tournamentId: $tournamentId) {
    tournament {
      id
      title
    }
    tables {
      table {
        id
        tableNumber
        maxSeats
      }
      seats {
        assignment {
          userId
          clubPlayerId
          seatNumber
          stackSize
        }
        displayName
        player {
          id
          firstName
          lastName
        }
      }
    }
    unassignedPlayers {
      clubPlayerId
      displayName
      user {
        id
        firstName
        lastName
      }
    }
  }
}

query GetTournamentBounties($tournamentId: ID!) {
  tournamentBounties(tournamentId: $tournamentId) {
    id
    hunterClubPlayerId
    victimClubPlayerId
    hunterName
    victimName
    amountCents
    createdAt
  }
}
