query GetMe {
  me {
    id
    email
    username
    firstName
    lastName
    phone
    isActive
    role
    clubRole
    managedClub {
      id
      name
      city
      plan
      subscriptionExpiresAt
    }
  }
}
